secrets:
  Db-password:
    file: ./secrets/POSTGRES_PASSWORD
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    secrets:
      - source: Db-password
        target: POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
      start_interval: 1s
    ports:
      - "5432:5432"
  netting-engine:
    build: .
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_interval: 1s
      start_period: 15s
    env_file:
      - .env
    secrets:
      - source: Db-password
        target: POSTGRES_PASSWORD
    ports :
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy