spring.application.name=netting-engine

# datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/netting-engine}
spring.datasource.username=${POSTGRES_USER:netting-engine}

# jpa
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create

# flyway
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

server.port=8080